[colors.bright]
black = "#a59f91"
blue = "#99AB90"
cyan = "#E1D2AC"
green = "#B66588"
magenta = "#CBAB99"
red = "#988E76"
white = "#ece4d0"
yellow = "#6F9385"

[colors.normal]
black = "#0d0f10"
blue = "#99AB90"
cyan = "#E1D2AC"
green = "#B66588"
magenta = "#CBAB99"
red = "#988E76"
white = "#ece4d0"
yellow = "#6F9385"

[colors.primary]
background = "#0d0f10"
foreground = "#ece4d0"
